### ISSUE TITLE
Can't install etcher on raspbian

### ISSUE THREAD

**Issue by AedanBarr** [balena-io/etcher#3182] opened 2020-05-28 22:14 UTC
Hello, I followed the instructions on how to install etcher on linux, but it keeps saying that the package it unavailable. Any help would help right now. Thanks
![2020-05-28_18-11](https://user-images.githubusercontent.com/59069724/83199385-12c98700-a10f-11ea-99c7-bb0d8982e3f5.png)

**Comment by lurch** [comment] 2020-05-28 22:17
Etcher isn't yet packaged for ARM architectures #2870 (as used by the Raspberry Pi).

**Comment by zvin** [comment] 2020-05-29 09:43
Closing as this is a duplicate of #2870
You can still build etcher from source: clone the repo and run `make electron-build`

**Closed by zvin** 2020-05-29 09:43 UTC
