### ISSUE TITLE
Allow PolKit to identify etcher temporary file

### ISSUE THREAD

**Issue by ffissore** [balena-io/etcher#3065] opened 2020-02-06 10:09 UTC
Etcher creates a temporary file after hitting the "flash" button. Running that file requires superuser privileges.
However the file name is totally random, which makes it impossible to set up a PolKit rule that allows normal users to run that file without asking them root password
Investigate how to set up such a rule, for example by prefixing the name of the temporary file with a known value

- **Etcher version:** 1.5.51
- **Operating system and architecture:** linux

**Comment by lurch** [comment] 2020-02-06 12:05
Is that what #3047 was attempting to do? :man_shrugging:

**Comment by ffissore** [comment] 2020-02-06 13:29
It looks like so, and it's now part of #3064. Let's see if prefix does the trick, otherwise we'll need to look for something else

**Comment by lurch** [comment] 2020-02-06 14:21
That PR has now been merged, so I guess it's included in Etcher 1.5.76 ? :man_shrugging:

**Comment by thundron** [comment] 2020-02-06 14:28
Correct @lurch , closing

**Comment by thundron** [comment] 2020-03-27 12:04
Did the prefix solve the issue @ffissore ?

**Comment by ffissore** [comment] 2020-03-27 15:18
I'll ping the [forum user](https://forums.balena.io/t/how-to-identify-etcher-with-polkit/58363/28) that requested this change. What's the prefix on linux?

**Comment by thundron** [comment] 2020-04-02 14:06
It's `balena-etcher-electron-`, closing so this gets propagated

**Closed by thundron** 2020-04-02 14:06 UTC

**Comment by georgiats** [comment] 2020-05-05 10:16
Not sure if it helps, but the user has found a resolution and reported it here. https://forums.balena.io/t/how-to-identify-etcher-with-polkit/58363/30

**Comment by thundron** [comment] 2020-05-06 10:52
I guess the prefix is working as intended then.
Thank you @georgiats
