### ISSUE TITLE
Cannot read property 'UPDATE_NOTIFIER_SLEEP_DAYS' of undefined

### ISSUE THREAD

**Issue by ealmonte32** [balena-io/etcher#2564] opened 2018-11-27 15:48 UTC
- **Etcher version:**  = 1.4.7
- **Operating system and architecture:** = Windows 7 32-bit
- **Image flashed:** = did not get to this part but just a regular raspbian iso

Attached is screenshot of error.

![etcher_error_update_notifier_sleep_days](https://user-images.githubusercontent.com/24350198/49093497-34a03000-f232-11e8-9f9e-e8e6ab2abce4.png)

**Comment by thundron** [comment] 2018-11-27 16:21
You can safely dismiss the dialogue, it's the update notification that isn't currently working properly but will be fixed once 1.4.9 is out.
Meanwhile you can upgrade to 1.4.8 to get rid of it
Closing as duplicate of https://github.com/balena-io/etcher/issues/2559

**Closed by thundron** 2018-11-27 16:21 UTC
