### ISSUE TITLE
You're not authorized to perform this operation error on macOS 10.15.1 Beta Version 19B77a

### ISSUE THREAD

**Issue by wpzhhhhh** [balena-io/etcher#2954] opened 2019-10-29 11:27 UTC
- **Etcher version:1.5.0** 
- **Operating system and architecture:macOS 10.15.1 Beta Version 19B77a** 
- **Image flashed: Raspbian Desktop** 
- **Do you see any meaningful error information in the DevTools? No.** 
![截屏2019-10-2919 22 55](https://user-images.githubusercontent.com/44501215/67762968-8c1dd000-fa81-11e9-995a-e8dac7598310.png)

**Comment by lurch** [comment] 2019-10-29 11:32
Duplicate of #2833

**Closed** 2019-11-01 08:29 UTC
