### ISSUE TITLE
"contact the Etcher team if the problem persists"

### ISSUE THREAD

**Issue by 404ClickBait** [balena-io/etcher#2907] opened 2019-09-17 14:46 UTC
- **Etcher version:** 1.5.57
- **Operating system and architecture:** Windows 10
- **Image flashed:** hassbian version 2019-07-02
- **Do you see any meaningful error information in the DevTools?** 

"The writer process ended unexpectedly.  Please try again, and contact the Etcher team if the problem persists"

It's fine, I'll just continue using Win32DiskImager...

**Comment by lurch** [comment] 2019-09-17 15:05
See also: https://github.com/balena-io/etcher/search?q=The+writer+process+ended+unexpectedly&type=Issues

**Comment by thundron** [comment] 2019-09-18 14:43
@404ClickBait If you're willing to paste here the logs from the application, we could try to fix/reproduce the issue, otherwise it's understandable and we can close this I guess in favor of already open issues

**Comment by 404ClickBait** [comment] 2019-09-18 17:47
Let me know if you would like me to get this for your benefit.  To be honest I already have a tool (or two) that do everything I need so it would just be to help you out.

Best regards,
Kyle

**Comment by lurch** [comment] 2019-09-18 21:45
@404ClickBait You might want to edit your email address out of that last message, to stop it being picked up by spambots?

**Comment by 404ClickBait** [comment] 2019-09-19 13:54
Hello,

I’m sorry, what does that mean – to “edit your email address out of that last message” – is this email posted publicly?

Thanks,
kyle

**Comment by lurch** [comment] 2019-09-19 14:11
Yes, see https://github.com/balena-io/etcher/issues/2907

**Comment by 404ClickBait** [comment] 2019-09-19 14:15
> Yes, see #2907

Thank you for letting me know!

**Comment by Xu-TikT** [comment] 2020-08-12 00:36
1.5.102 Mac version works for me

**Comment by thundron** [comment] 2020-08-12 09:05
Thanks for chiming in @Xu-TikT, although this issue is about a different OS (Windows 10).
It's clear though that there have been several other versions released since this issue was opened, so I'll close this.

FWIW usually (not always of course) that error comes from some specific settings on Windows that prevent Etcher from working.

**Closed by thundron** 2020-08-12 09:05 UTC
