### ISSUE TITLE
Provide builds for Apple Silicon Macs

### ISSUE THREAD

**Issue by realJustinLee** [balena-io/etcher#3728] opened 2022-03-15 16:36 UTC

**Comment by mcraa** [comment] 2022-03-15 16:39
see #3593 and #3714

**Comment by DaveFlashNL** [comment] 2022-03-22 09:43
like to put my voice here as well

**Comment by dangost** [comment] 2022-03-24 23:27
I can build. But idk how to build electron app

**Comment by thedocbwarren** [comment] 2022-03-31 05:20
I'm building and maintaining under community builds:

https://github.com/balena-io/etcher/issues/3714

**Comment by Kurokosama** [comment] 2022-05-09 06:08
like to put my voice here as well

**Comment by core-code** [comment] 2022-10-10 16:50
this is a duplicate of #3593

**Comment by thedocbwarren** [comment] 2023-07-28 21:49
If the plan is to do this soon then I'm ok with it, but the signing procedure broke community builds for use on native.  I've not been able to build since the change over and sign an actual deployment.

**Comment by nearlystardust** [comment] 2023-11-07 19:47
If this is mentioning Apple's code signing, just instruct users to ad-hoc sign the app. 

I've heard people complain that macOS doesn't allow unsigned `arm64` code to run, but that doesn't seem to be my experience on macOS Sonoma (the newest OS version as of late 2023).

**Closed** 2023-12-21 16:41 UTC

**Comment by core-code** [comment] 2023-12-21 21:06
could you leave this open until a real AppleSilicon or Universal build exists?

**Comment by dfunckt** [comment] 2023-12-22 07:03
There is an arm64 build for macOS, check the assets of the 1.19.0 release.

**Comment by core-code** [comment] 2023-12-22 10:05
thanks. it is still marked as "Pre-release"?

**Comment by dfunckt** [comment] 2023-12-22 10:30
Yes.

**Comment by HVR88** [comment] 2024-06-25 19:26
The arm64 build is over 300MB in size.  What? Even with graphics resources it's somewhat crazy that a little image writing app with this functionality is over 10-20MB. Are you shipping an entire linux distro inside the Mac bundle along with QEMU/KVM so it can run its own virtual machine? Pretty sure even that would be under 300MB.

**Comment by hronro** [comment] 2024-06-26 03:05
@HVR88 They use Electron as the GUI framework, resulting in a HelloWorld app that exceeds 100 MB.
