### ISSUE TITLE
Etcher not flashing on mac

### ISSUE THREAD

**Issue by happyduck1** [balena-io/etcher#3068] opened 2020-02-14 20:58 UTC
- **Version 1.5.76** 
- **Operating system and architecture:Mac os** 
- **rasberry pi image file** 
Hi, when installing the rasberry pi .img file (came from .zip) 
I select the .img file, then the drive I want then click flash, enter my mac password, then it goes back to the last image.
![Screen Shot 2020-02-14 at 3 55 23 PM](https://user-images.githubusercontent.com/61066437/74567018-d3ea3980-4f42-11ea-8ed8-ca06af9cbb56.png)
![Screen Shot 2020-02-14 at 3 55 43 PM](https://user-images.githubusercontent.com/61066437/74567020-d3ea3980-4f42-11ea-9693-04d185671ee9.png)
![Screen Shot 2020-02-14 at 3 56 17 PM](https://user-images.githubusercontent.com/61066437/74567021-d482d000-4f42-11ea-8062-f53999226906.png)
![Screen Shot 2020-02-14 at 3 56 28 PM](https://user-images.githubusercontent.com/61066437/74567022-d482d000-4f42-11ea-98c2-f0e281507961.png)

**Comment by uYtLD9zS** [comment] 2020-02-14 22:00
I am having the same problem.
Operating system and architecture:MacOS Catalina
pfSense image file

**Comment by uYtLD9zS** [comment] 2020-02-14 22:30
@happyduck1 - make sure you are logged in to an administrator account

**Comment by KondorB** [comment] 2020-02-20 16:41
Have the same problem here. Earlier versions were asking for admin login and password and worked fine afterwards. So, why this version just assumes running from admin?

**Comment by lurch** [comment] 2020-02-20 17:14
More info in #3067

**Comment by rubysims** [comment] 2020-03-12 01:59
what is an a administrator account

**Comment by ieaves** [comment] 2020-05-25 20:54
@lurch #3067 seems to indicate an issue on MacOS, am I reading that correctly? I'm having a similar issue to all of those above still and have exhausted the debugging steps that appear available. Just trying to make sure I haven't missed anything before giving up.

**Comment by lurch** [comment] 2020-05-26 12:11
@ieaves I'm not an Etcher developer (and I don't have a Mac), but AFAIK the most up-to-date info about these MacOS issues is in #3107 

@thundron Maybe this should be closed as a duplicate of #3107 ?

**Comment by thundron** [comment] 2020-05-29 17:41
Definitely, refer to the other issue for more information

**Closed by thundron** 2020-05-29 17:41 UTC
