### ISSUE TITLE
macOS: version. 1.5.74 app not initializing 

### ISSUE THREAD

**Issue by RandyMcMillan** [balena-io/etcher#3056] opened 2020-02-04 23:13 UTC
I have a fresh install of Mojave 10.14.6 (18G103) running.
[-1580857850329.log](https://github.com/balena-io/etcher/files/4156610/-1580857850329.log)

/Applications/balenaEtcher.app/Contents/Resources/app/node_modules/raven-js/dist/raven.js:58 {"stack":"TypeError: Cannot convert undefined or null to object\n    at Function.entries (<anonymous>)\n    at Object.init (file:///Applications/balenaEtcher.app/Contents/Resources/app/generated/gui.js:3951:49)\n    at main (file:///Applications/balenaEtcher.app/Contents/Resources/app/generated/gui.js:3633:12)","message":"Cannot convert undefined or null to object"}
console.<computed> @ /Applications/balenaEtcher.app/Contents/Resources/app/node_modules/raven-js/dist/raven.js:58

![Screen Shot 2020-02-04 at 3 06 35 PM](https://user-images.githubusercontent.com/152159/73795678-100de500-4760-11ea-81e2-d30d74f620ae.png)
![Screen Shot 2020-02-04 at 3 06 14 PM](https://user-images.githubusercontent.com/152159/73795708-2156f180-4760-11ea-892b-0f1c037383ff.png)

**Comment by lurch** [comment] 2020-02-04 23:43
Probably a duplicate of #3057 ?

**Closed** 2020-02-05 12:35 UTC
