### ISSUE TITLE
Suggestion : add backup image support (read) 

### ISSUE THREAD

**Issue by Askmewho** [balena-io/etcher#2781] opened 2019-05-12 22:22 UTC
This is an old requested feature. But being the best burning crossplatform tool than even run on the rpi platform, woulb be awesome if it add backup support, and if it could shrink the image automatically after reading it would be double awesome. Thanks.

**Comment by lurch** [comment] 2019-05-13 09:20
Duplicate of #266 ?

**Comment by zvin** [comment] 2019-05-13 10:11
Closing as duplicate of #266

**Closed by zvin** 2019-05-13 10:11 UTC
