### ISSUE TITLE
Unable to install in 18.04

### ISSUE THREAD

**Issue by meetdilip** [balena-io/etcher#3096] opened 2020-03-03 16:57 UTC
- **Etcher version:**  1.5.79
- **Operating system and architecture:** Ubuntu 18.04 64 bit
- **Image flashed:** None
- **Do you see any meaningful error information in the DevTools?** I am unable to install

I got up to `sudo apt-get update` for Debian / Ubuntu and then got an error when tried the last step
```

Get:41 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 DEP-11 Metadata [2,464 B]
Reading package lists... Done                                                  
E: The repository 'https://deb.etcher.io stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
myName@my-PC-Name:~$ sudo apt-get install balena-etcher-electron
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package balena-etcher-electron
```

**Comment by lurch** [comment] 2020-03-03 16:58
Duplicate of #3078

**Comment by nekromoff** [comment] 2020-03-05 13:23
Same for 16.04

**Comment by nekromoff** [comment] 2020-03-05 13:25
https://dl.bintray.com/etcher/debian/etcher-electron_1.4.3_amd64.deb
Forbidden!

**Comment by lurch** [comment] 2020-03-05 13:27
See my previous comment...

**Comment by nekromoff** [comment] 2020-03-05 13:52
It was a complaint 9 days ago. If your repo is unable to be fixed in 9
days, then maybe change the repo provider.

**Comment by thundron** [comment] 2020-03-05 15:44
See #3078 as mentioned.
Meanwhile you can update/install through the release page.
Thank you for the patience

**Closed by thundron** 2020-03-05 15:44 UTC
