### ISSUE TITLE
shasum 

### ISSUE THREAD

**Issue by lttrest07** [balena-io/etcher#3123] opened 2020-04-18 16:48 UTC
Is it possible to get the shasum for the files? OR do they currently exist?

**Comment by lurch** [comment] 2020-04-20 21:18
Duplicate of #2826 ?

**Comment by lttrest07** [comment] 2020-04-20 21:35
> Duplicate of #2826 ?

Looks like your right. However for 1.5.81 doesn't look like mac has a checksum for the .dmg and doesn't look like the one for mac .zip matches.

**Closed** 2021-05-17 09:59 UTC
