### ISSUE TITLE
linux

### ISSUE THREAD

**Issue by dsgsdg3** [balena-io/etcher#3666] opened 2021-12-28 03:31 UTC
balena-etcher-electron-**1.7.0**-linux-x64.zip
![balenaEtcher-1 7 0-x64](https://user-images.githubusercontent.com/96667633/147525013-bdbda645-182d-4f2d-a085-450a3cdcb582.png)

balena-etcher-electron-**1.7.2**-linux-x64.zip - **ERROR**
![balenaEtcher-1 7 2-x64 ошибка](https://user-images.githubusercontent.com/96667633/147525091-e239ced0-c0cd-4b0c-9d92-7af0cb513210.png)

**Comment by lurch** [comment] 2021-12-28 13:20
Duplicate of #3648 ?

**Comment by dsgsdg3** [comment] 2021-12-28 14:59
Yes

**Closed** 2021-12-29 15:31 UTC
