### ISSUE TITLE
Access denied when trying to refresh etcher repo on OpenSuse Tumbleweed

### ISSUE THREAD

**Issue by elektronaut69** [balena-io/etcher#3257] opened 2020-07-21 13:38 UTC
- **Etcher version:** 
- **Operating system and architecture:** 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?** 

When trying to refresh the repo for OpenSuse Tubleweed I get an "Access denied" error.

**Comment by lurch** [comment] 2020-07-21 13:41
Duplicate of #3244

**Closed** 2020-07-21 14:08 UTC
