### ISSUE TITLE
RPM repo 403

### ISSUE THREAD

**Issue by jtagcat** [balena-io/etcher#3081] opened 2020-02-24 08:58 UTC
- **Operating system and architecture:** Fedora 31 x64
The RPM repository is not working:
```
Errors during downloading metadata for repository 'etcher-rpm':
  - Status code: 403 for https://dl.bintray.com/etcher/redhat/repodata/repomd.xml (IP: 52.28.187.224)
Error: Failed to download metadata for repo 'etcher-rpm': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

**Comment by lurch** [comment] 2020-02-24 11:11
Probably a duplicate of #3078 ?

**Closed** 2020-02-24 11:57 UTC

**Comment by G-Pereira** [comment] 2020-07-25 23:33
Any solution yet? I am still having this issue on Fedora 32

**Comment by lurch** [comment] 2020-07-25 23:37
See #3244
