### ISSUE TITLE
Does Etcher support on ARM processor Raspberry Pi

### ISSUE THREAD

**Issue by llks** [balena-io/etcher#2814] opened 2019-05-31 13:34 UTC
- **Etcher version: 1.5.43** 
- **Operating system and architecture: Raspberry Pi Processor, ARM architecture** 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?** 

_May i know this software has any version that can run on ARM processor in Raspberry Pi? My project need to run on that platform.
_

**Comment by lurch** [comment] 2019-05-31 14:14
Duplicate of #2748 ?

**Comment by thundron** [comment] 2019-06-03 08:58
Yes it is @lurch 
@llks We are experimenting building on ARM but for now we only ship x86/x64 packages.
Closing for now

**Closed by thundron** 2019-06-03 08:58 UTC

**Comment by llks** [comment] 2019-06-04 04:03
Ok, thanks! Can't wait for the new release to the ARM platform as the market use so many ARM platform! May i know is there any target date for the ARM platform release?

**Comment by thundron** [comment] 2019-06-04 12:59
@llks As of now we're not working on the package itself so it's not really something we're planning to distribute (as of now). We'll surely let users know shall that happen!
