### ISSUE TITLE
**** duplicate to issue 3078****repo fails since latest update 1.5.76 fedora 30

### ISSUE THREAD

**Issue by CanonCan** [balena-io/etcher#3083] opened 2020-02-24 21:11 UTC
- **Etcher version:** repo
- **Operating system and architecture:** fedora 30 x86_64 kernel 5.4.19

running dnf update fails with this error 

```
sudo dnf update
etcher-rpm                                                                    
Errors during downloading metadata for repository 'etcher-rpm':
  - Status code: 403 for https://dl.bintray.com/etcher/redhat/repodata/repomd.xml (IP: 52.11.162.82)
Error: Failed to download metadata for repo 'etcher-rpm': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

**Comment by PeterSprague** [comment] 2020-02-24 21:13
Same, on Fedora 31

**Comment by JakeTrock** [comment] 2020-02-24 21:43
I am also experiencing this same problem with your Debian ppa. Would it be possible to release this to the snap store instead?
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package balena-etcher-electron is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'balena-etcher-electron' has no installation candidate
`

**Comment by GammaGames** [comment] 2020-02-24 22:01
Looks like a duplicate of #3078

**Comment by lurch** [comment] 2020-02-25 01:49
> Would it be possible to release this to the snap store instead?

For snap, see #415

**Comment by CanonCan** [comment] 2020-02-25 02:30
> Looks like a duplicate of #3078

Sorry I missed that was skimming the issues when couldn’t find it I posted here but either way no solution in sight it seems

**Comment by thundron** [comment] 2020-02-25 11:42
Thank you for the report, working on it, please refer to the other issue

**Closed by thundron** 2020-02-25 11:42 UTC
