### ISSUE TITLE
403 Repository Forbidden in 19 july 2020

### ISSUE THREAD

**Issue by PauloCreto-Linux** [balena-io/etcher#3250] opened 2020-07-19 13:52 UTC
- **Etcher version: 1.50
- **Operating system and architecture: amd64
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?** 

The 403 error problem for the balenaEtcher repository is still causing problems today

Check out my tip on the BigLinux forum based on ubuntu

[https://forum.biglinux.com.br/t/dica-adicionando-o-repositorio-do-balenaetcher/401?u=creto](url)

See you later

**Comment by lurch** [comment] 2020-07-19 13:55
Duplicate of #3244

**Closed** 2020-07-19 14:04 UTC

**Comment by PauloCreto-Linux** [comment] 2020-07-19 14:06
Thank's to inform

Closed
