### ISSUE TITLE
download image on disk partition

### ISSUE THREAD

**Issue by StrRoma** [balena-io/etcher#3457] opened 2021-03-14 17:12 UTC
- **Etcher version:** 1.5.116
- **Operating system and architecture:** macOS Catolina 10.15.6
- **Image flashed:** ubuntu 20.04.2.0
- **Do you see any meaningful error information in the DevTools?** 

How can I install image not on whole ssd? I want to install image only on part of my ssd.

**Comment by lurch** [comment] 2021-03-14 18:28
Duplicate of #3415

**Closed** 2021-03-15 15:59 UTC
