### ISSUE TITLE
Etcher not work on macOS Catalina

### ISSUE THREAD

**Issue by mrdong916** [balena-io/etcher#2913] opened 2019-09-29 08:27 UTC
- **Etcher version: 1.5.57** 
- **Operating system and architecture: macOS** 
- **Image flashed: https://mirrors.tuna.tsinghua.edu.cn/deepin-cd/15.11/deepin-15.11-amd64.iso** 
- **Do you see any meaningful error information in the DevTools?** 

Error: EPERM: operation not permitted, open '/dev/rdisk2

**Comment by RedcoatAsher** [comment] 2019-10-01 18:10
**+1**

**Comment by lurch** [comment] 2019-10-02 09:57
Duplicate of #2833 ?

**Comment by alexmuntean** [comment] 2019-10-09 20:03
i managed to flash by copying inside balenaetcher app itself and selecting it from there and disabling system integrity protection (command+r while restarting -> terminal -> csrutil disable)

**Comment by mrdong916** [comment] 2019-10-10 00:56
> Duplicate of #2833 ?

Different versions

**Comment by MarcGodard** [comment] 2019-10-11 14:44
Just tried the latest version and not working.

**Comment by satmandu** [comment] 2019-10-11 14:59
FYI Running ```sudo /Applications/balenaEtcher.app/Contents/MacOS/balenaEtcher``` appears to work.

**Comment by kunau** [comment] 2019-10-11 23:19
The above fix did not work under Catalina, still see this:
![Screen Shot 2019-10-11 at 6 19 33 PM](https://user-images.githubusercontent.com/656846/66690131-aff4af80-ec53-11e9-854c-4376e63050ec.png)

**Comment by radeksalomon** [comment] 2019-10-12 12:28
Did you try to add Full Disk Access to Balena Etcher?
<img width="646" alt="Screenshot 2019-10-12 at 14 21 31" src="https://user-images.githubusercontent.com/3299963/66701405-7fb51b80-ecfc-11e9-92f6-c6c4be24cbd2.png">

**Comment by yabbah** [comment] 2019-10-12 12:44
I try burn ubuntu and vmware on 2 different sticks. I always get the error message: "Something went wrong. If it is a compressed image, please check that the archive is not corrupted." 
Can anyone burn images in catalina?

**Comment by ivanbacher** [comment] 2019-10-12 14:15
+1

**Comment by satmandu** [comment] 2019-10-12 18:03
> Did you try to grant Full Disk Access to Balena Etcher?
> <img alt="Screenshot 2019-10-12 at 14 21 31" width="646" src="https://user-images.githubusercontent.com/3299963/66701405-7fb51b80-ecfc-11e9-92f6-c6c4be24cbd2.png">

Granting full disk access doesn't appear to make a difference.

**Comment by yabbah** [comment] 2019-10-12 18:08
Yes tried that. No difference.

**Comment by stiucsib86** [comment] 2019-10-13 15:19
> FYI Running `sudo /Applications/balenaEtcher.app/Contents/MacOS/balenaEtcher` appears to work.

This works. Catalina will prompt for additional permission prior to flashing.

**Comment by kunau** [comment] 2019-10-14 02:20
The above does not work on my system, cannot 'check it for malicious software'.

**Comment by lurch** [comment] 2019-10-14 08:07
> cannot 'check it for malicious software'.

#2911

**Comment by thundron** [comment] 2019-10-19 10:42
Closing as duplicate of #2833 , we have a PR open that will solve issues with macOS Catalina

**Closed by thundron** 2019-10-19 10:42 UTC

**Comment by osxrox** [comment] 2019-10-22 16:51
sudo /Applications/balenaEtcher.app/Contents/MacOS/balenaEtcher

Worked for me burningan ISO to a USB stick.

**Comment by maximilliangeorge** [comment] 2020-11-30 10:50
> > Did you try to grant Full Disk Access to Balena Etcher?
> > <img alt="Screenshot 2019-10-12 at 14 21 31" width="646" src="https://user-images.githubusercontent.com/3299963/66701405-7fb51b80-ecfc-11e9-92f6-c6c4be24cbd2.png">
> 
> Granting full disk access doesn't appear to make a difference.

This worked for me though. Thanks!
