### ISSUE TITLE
“balenaEtcher” can’t be opened because Apple cannot check it for malicious software.

### ISSUE THREAD

**Issue by e3b0c442** [balena-io/etcher#2911] opened 2019-09-25 03:59 UTC
- **Etcher version:** 1.5.57
- **Operating system and architecture:** macOS Catalina 10.15 beta build 19A573a
- **Image flashed:** n/a
- **Do you see any meaningful error information in the DevTools?** n/a

Etcher will not open on the latest macOS beta, with the error:
“balenaEtcher” can’t be opened because Apple cannot check it for malicious software.

This was downloaded fresh tonight.

Not sure what else I can provide for troubleshooting as macOS prevented the application from even launching.

**Comment by lurch** [comment] 2019-09-25 07:23
See https://github.com/balena-io/etcher/issues/2833#issuecomment-520375994

**Comment by thundron** [comment] 2019-09-25 11:02
Closing in favor of the other issue open, also see https://github.com/balena-io/etcher/issues/2833#issuecomment-511152047 for a temp workaround

**Comment by e3b0c442** [comment] 2019-09-25 11:38
I feel like this may be a different issue. The symptom I am describing is not laid out in any of the comments there, and that workaround does not work; `sudo` has the same result.

**Comment by thundron** [comment] 2019-09-25 15:13
Hmmm, right @e3b0c442 . A quick search led me to this https://apple.stackexchange.com/questions/366542/install-spotify-cant-be-opened-because-apple-cannot-check-it-for-malicious-so so it looks like we'll have to wait a bit for that (app notarisation) to happen on Etcher. I'll keep this open then until we update that part of the OSX package

**Comment by michaelfm1211** [comment] 2019-10-09 01:45
If you right click(Control Click) on the Etcher app then click "Open" you will get a different dialog which has the option to continue to open Etcher.

**Comment by dtaivpp** [comment] 2019-10-21 12:50
Hey all, here is a workaround to install Etcher:

`xattr -d com.apple.quarantine Downloads/<your installer>.pkg`

After executing this line which is pointed at your installer image you will be able to run it. It deletes the 'quarentine' attribute that Apple has set that is disallowing it from running.

**Comment by thundron** [comment] 2019-10-21 13:33
@dtaivpp Correct, the issue will stay open until #2939 (or a substitute of that w/ Electron 6 that we're working on as well) will be ready/merged

**Comment by gorsim** [comment] 2019-10-25 16:52
> Hey all, here is a workaround to install Etcher:
> 
> `xattr -d com.apple.quarantine Downloads/<your installer>.pkg`
> 
> After executing this line which is pointed at your installer image you will be able to run it. It deletes the 'quarentine' attribute that Apple has set that is disallowing it from running.
> 
> @thundron I think you should keep this one open as #2833 is a disk permissions error and this one is related to the app being registered with Apple.

Thanks for this.  Do you put the full name of the .dmg file in the <your installer>?  eg `xattr -d com.apple.quarantine Downloads/<balenaEtcher-1.5.59.dmg>.pkg`

**Comment by dtaivpp** [comment] 2019-10-25 17:44
@gorsim for the dmg you would remove.pkg and just use .dmg extension

**Comment by gorsim** [comment] 2019-10-25 19:39
> @gorsim for the dmg you would remove.pkg and just use .dmg extension

Thanks David.  Annoyingly it didn't work - still said the same thing.  This is the terminal dialogue - the first time it did seem to do something then when I tried again said no such xattr.  I ran it then re-installed balenaEtcher-1.5.59.dmg and when I opened it the message said “balenaEtcher” can’t be opened because Apple cannot check it for malicious software.

 Any ideas?  (Sorry I am not very used to command mode!)


simons-MBP:~ simonnonadmin$ xattr -d com.apple.quarantine Downloads/balenaEtcher-1.5.59.dmg
Simons-MBP:~ simonnonadmin$ xattr -d com.apple.quarantine Downloads/balenaEtcher-1.5.59.dmg
xattr: Downloads/balenaEtcher-1.5.59.dmg: No such xattr: com.apple.quarantine

**Comment by dtaivpp** [comment] 2019-10-25 19:58
@gorsim the first time it worked and removed the attribute. The second time you ran it, it was saying there is no such attribute because it had already been deleted. 

I would download, run the command once, and then attempt to open the dmg. I am unable to replicate any more as it seems my computer recognizes it as safe now

**Comment by gorsim** [comment] 2019-10-25 21:01
> @gorsim the first time it worked and removed the attribute. The second time you ran it, it was saying there is no such attribute because it had already been deleted.
> 
> I would download, run the command once, and then attempt to open the dmg. I am unable to replicate any more as it seems my computer recognizes it as safe now

Thank you so much David - it worked!

**Comment by gorsim** [comment] 2019-10-25 21:15
David - next problem I'm trying to convert CentOS-Userland-7-armv7hl-RaspberryPI-Minimal-4-1908-sda.raw.xz into an image file for a raspberry pi 4 (from herehttp://mirrors.coreix.net/centos-altarch/7.7.1908/isos/armhfp/)  but Etcher says it is corrupted.  I tried another file and it says the same thing.  Does yours work properly?

**Comment by whatwouldleedo** [comment] 2019-10-25 21:26
>     * **Etcher version:** 1.5.57
> 
>     * **Operating system and architecture:** macOS Catalina 10.15 beta build 19A573a
> 
>     * **Image flashed:** n/a
> 
>     * **Do you see any meaningful error information in the DevTools?** n/a
> 
> 
> Etcher will not open on the latest macOS beta, with the error:
> “balenaEtcher” can’t be opened because Apple cannot check it for malicious software.
> 
> This was downloaded fresh tonight.
> 
> Not sure what else I can provide for troubleshooting as macOS prevented the application from even launching.

Did you visit your System Preferences > Security & Privacy > then click allow. Try this method after you try to open your file.

**Comment by gorsim** [comment] 2019-10-25 22:02
> > ```
> > * **Etcher version:** 1.5.57
> > 
> > * **Operating system and architecture:** macOS Catalina 10.15 beta build 19A573a
> > 
> > * **Image flashed:** n/a
> > 
> > * **Do you see any meaningful error information in the DevTools?** n/a
> > ```
> > 
> > 
> > Etcher will not open on the latest macOS beta, with the error:
> > “balenaEtcher” can’t be opened because Apple cannot check it for malicious software.
> > This was downloaded fresh tonight.
> > Not sure what else I can provide for troubleshooting as macOS prevented the application from even launching.
> 
> Did you visit your System Preferences > Security & Privacy > then click allow. Try this method after you try to open your file.

Thanks for your help - actually I sussed it out via another forum.  You need to run etcher using sudo when logged in as administrator then it works.  Cheers

**Comment by zvin** [comment] 2019-11-06 02:09
Duplicate of #2833

**Closed by zvin** 2019-11-06 02:09 UTC
