### ISSUE TITLE
This app doesn't load at startup (no GUI)

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [balena-io/etcher#3754] opened 2022-05-01 10:34 UTC
- **Etcher version:** 1.7.9
- **Operating system and architecture:** Windows 10 x64
- **Image flashed:** N/A
- **What do you think should have happened:**  Opened app
- **What happened:** Nothing via GUI (running via CMD is showed this problem)
- **CMD Message:**

(node:6324) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `balenaEtcher --trace-deprecation ...` to show where the warning was created)
[Axios v1.7.9] Transitional option 'clarifyTimeoutError' has been deprecated since v1.0.0 and will be removed in the near future
[Axios v1.7.9] Transitional option 'forcedJSONParsing' has been deprecated since v1.0.0 and will be removed in the near future
[Axios v1.7.9] Transitional option 'silentJSONParsing' has been deprecated since v1.0.0 and will be removed in the near future

- **Do you see any meaningful error information in the DevTools?** 
 App is not opened so I didn't see anyhing

Same issue here: #3749

**Comment by mcraa** [comment] 2022-05-02 09:35
then duplicate of #3749

at the same time, thanks for the details

**Closed by mcraa** 2022-05-02 09:35 UTC
