### ISSUE TITLE
Can not find icon.png

### ISSUE THREAD

**Issue by NelDav** [balena-io/etcher#3080] opened 2020-02-24 00:01 UTC
- **Etcher version:** 1.5.79
- **Operating system and architecture:** Windows 10
- **Image flashed:** 2020-02-13-raspbian-buster-lite
- **Do you see any meaningful error information in the DevTools?** 
> GET file:///C:/Users/DN/AppData/Local/Programs/balena-etcher/resources/app.asar/lib/assets/icon.png net::ERR_FILE_NOT_FOUND

I think etcher should not crash because of a missing image

**Comment by lurch** [comment] 2020-02-24 11:18
Possibly a duplicate of #3039 ? I wonder why more people aren't getting this error? :man_shrugging:

**Comment by thundron** [comment] 2020-02-25 12:12
When does this happen?

**Comment by NelDav** [comment] 2020-03-07 11:21
It happens, directly bevore flashing.

I solved the problem by adding Balena as exception in "Allow an app through Controlled folder acces". (Settings->Update & Security->Windows Security->Virus & threat protection->Manage Settings->Controlled folder access->Allow an app through Controlled folder acces)

**Comment by lurch** [comment] 2020-03-08 18:37
Ahhhh. Seems like tweaking that setting somehow fixes many Etcher problems? https://github.com/balena-io/etcher/search?q=controlled+folder+access&type=Issues

**Comment by wahyudwikrisnanto** [comment] 2020-04-30 01:23
Im still had the problem even my setting on controlled folder access is turned off

**Comment by thundron** [comment] 2020-05-06 11:02
@wahyudwikrisnanto have you tried opening as admin?

**Comment by zvin** [comment] 2020-05-06 13:54
fixed in 1.5.84

**Closed by zvin** 2020-05-06 13:54 UTC
