### ISSUE TITLE
RPM Packages instructions install older version of Etcher

### ISSUE THREAD

**Issue by TheRoarkster** [balena-io/etcher#2572] opened 2018-12-01 17:28 UTC
Trying to update to the balena version of etcher via repos.  

The instructions provided here (https://github.com/balena-io/etcher#redhat-rhel-and-fedora-based-package-repository-gnulinux-x86x64) install the older version.  

As a result, etcher still throws the error from these issues:
```
Error message when try to open file [Cannot read property 'UPDATE_NOTIFIER_SLEEP_DAYS' of undefined]
#2568 by szotsaki was closed 2 days ago 
 2
Cannot read property 'UPDATE_NOTIFIER_SLEEP_DAYS' of undefined
#2564 by ealmonte32 was closed 4 days ago 
 1
cannot read property of 'UPDATE_NOTIFIER_SLEEP_DAYS' undefined
#2563 by jobvanellen was closed 4 days ago 
 3
Cannot read property 'UPDATE_NOTIFIER_SLEEP_DAYS' of undefined
#2559 by jlerigo was closed 5 days ago
``` 

Solution:  update the repos and/or the instructions to point to the newer version of etcher.

**Comment by lurch** [comment] 2018-12-03 12:42
Duplicate of #2540 ?

**Comment by thundron** [comment] 2018-12-03 16:42
Yep, the next update will fix the notification error and will be published to that repository too.
We didn't put 1.4.5+ versions there as they still have the broken notification

**Closed** 2018-12-03 16:42 UTC
