### ISSUE TITLE
gz "Archive Corrupted"

### ISSUE THREAD

**Issue by maxgrass** [balena-io/etcher#2962] opened 2019-11-04 23:19 UTC
<img width="580" alt="Screenshot 2019-11-05 at 00 13 48" src="https://user-images.githubusercontent.com/169885/68166017-52f1ce00-ff61-11e9-9216-86e2b99199f4.png">

- **Etcher version: 1.5.60** 
- **Operating system and architecture: macos 10.15** 
- **Image flashed:LibreELEC-RPi2.arm-9.1.502.img** 
- **Do you see any meaningful error information in the DevTools?** 

{"stack":"Error: EPERM: operation not permitted, open '/Users/bla/Downloads/LibreELEC-RPi2.arm-9.1.502.img.gz'","message":"EPERM: operation not permitted, open '/Users/bla/Downloads/LibreELEC-RPi2.arm-9.1.502.img.gz'","name":"Error","code":"EPERM","syscall":"open","errno":-1,"image":"LibreELEC-RPi2.arm-9.1.502.img.gz"}

Mac Security:
Balena has access to removable media, setting full disk access doesn't help.
The problem exists for months now.

Flashing via terminal works perfectly.

**Comment by lurch** [comment] 2019-11-05 02:06
> Operating system and architecture: macos 10.15

Duplicate of #2833 ?

**Comment by zvin** [comment] 2019-11-06 02:01
Duplicate of #2833

**Closed by zvin** 2019-11-06 02:01 UTC
