### ISSUE TITLE
Installation problem in newer versions

### ISSUE THREAD

**Issue by r1versEdge** [balena-io/etcher#3179] opened 2020-05-27 14:14 UTC
- **Last couple releases, ever since beginning of year** 
- **Kali Linux, amd64** 
- **No image, problem with installation** 
- **Required libpango1.0-0 to be installed, libpango is installed, it's asking for libpango1.0-0 when it should be asking for libpango-1.0-0 in the dependencies, this makes it so it won't install because of broken dependencies, one of the developers must have misspelled the dependency so now it won't install or work**

**Comment by lurch** [comment] 2020-05-27 15:52
Duplicate of #3119 which has been fixed. What version of Etcher are you trying to use?

Looks like there's still problems with the bintray repo though (see the discussion in #3133 ), so try downloading the latest `.deb` from https://github.com/balena-io/etcher/releases

**Comment by r1versEdge** [comment] 2020-05-27 15:56
Ok, thanks for the help

**Closed** 2020-05-29 17:10 UTC
