### ISSUE TITLE
Built-in information would be welcome

### ISSUE THREAD

**Issue by Ricky-Tigg** [balena-io/etcher#2969] opened 2019-11-13 08:10 UTC
_Tested:_  balenaEtcher-1.5.63-x64.AppImage under Wayland server.

_Enhancement request_ –  Under icon illustrating  "**?**"are traditionally expected **built-in** information. Access to that information relies on an established internet connection.

![balenaEtcher-1 5 63-x64 AppImage_interface](https://user-images.githubusercontent.com/26058215/68742493-fb0a3580-05f8-11ea-9d6d-73d389398281.png)

Be the product targeted for enterprise or home uses, at the very least, presence of categories related  to _[licence](https://github.com/balena-io/etcher/blob/master/LICENSE)_, _version_, and _architecture_ would be relevant.  _Version release date_, _OS_ and _Help_, while a bit less relevant, are worth to be mentioned as well.

_Help_ would mention that the software in its free variant, does not support multi-boot to device partition.

**Comment by lurch** [comment] 2019-11-13 13:55
I _think_ you're asking for an offline help page, rather than the :grey_question: icon taking you to an online URL, as it does currently?
Or is this some Wayland-specific request? :man_shrugging: 

> software in its free variant

AFAIK there isn't any other variant??

**Comment by Ricky-Tigg** [comment] 2019-11-14 07:01
Information to be available without **to have** to rely on an established internet connection; that would be what you mentioned as _off-line_. Mention of _Wayland_ was there in case a developer would have needed such information. On that [page](https://www.balena.io/etcher/pro), variant labelled "Pro" was exhibited.

**Comment by lurch** [comment] 2019-11-14 11:20
> On that page, variant labelled "Pro" was exhibited.

AIUI "Etcher Pro" is the hardware that they're building, but it'll still run the same (OpenSource) software as "regular Etcher"? ping @thundron @zvin

**Comment by Ricky-Tigg** [comment] 2019-11-14 12:19
I red there statement "Write to multiple cards or usb disks at once" fast enough to misinterpret it for  "Write to same USB device multiple ISO files at once."; then under _Help_, suggestion "_would mention that the software in its free variant, does not support multi-boot to device partition_" was irrelevant.

**Comment by lurch** [comment] 2019-11-14 14:06
Perhaps this is a duplicate of #2869 ?

**Comment by Ricky-Tigg** [comment] 2019-11-14 15:13
Since my previous comment there was no more object related to _Help_.

**Comment by lurch** [comment] 2019-11-14 15:16
Sorry, I should have clarified - both #2869 and #2969 seem to be related to the functionality of the "?" button? :man_shrugging:

**Comment by Ricky-Tigg** [comment] 2019-11-14 15:26
Don't be sorry, nothing bad! If for maintenance consideration classifying present report as duplicate nay serve your purpose, it has to done then.

**Closed** 2022-03-14 11:45 UTC
