### ISSUE TITLE
lingconf error on Ubuntu Budgie 18.04.2

### ISSUE THREAD

**Issue by sevku** [balena-io/etcher#2666] opened 2019-02-26 14:39 UTC
- **Etcher version:** 1.49
- **Operating system and architecture:** Ubuntu Budgie 18.04.2
- **Image flashed:** none
- **Do you see any meaningful error information in the DevTools?**
/tmp/.mount_GKCigu/usr/bin/balena-etcher-electron: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

**Comment by lurch** [comment] 2019-02-26 14:51
Duplicate of #2641 ?

**Closed** 2019-02-27 13:24 UTC
