### ISSUE TITLE
Feature request: Add AppImageUpdate

### ISSUE THREAD

**Issue by librafrog** [balena-io/etcher#3446] opened 2021-03-04 08:15 UTC
- **Etcher version:** balena-etcher-electron-1.5.116-linux-x64
- **Operating system and architecture:** Linux
- **Image flashed:** --
- **Do you see any meaningful error information in the DevTools?** No for the moment

Add the ability to update the appimage automaticlly from github as some project do offer for there projects regarding AppImages, rather for us users having to DW manually. I don't have problem with this still it would be a nice +_+

**Comment by lurch** [comment] 2021-03-04 08:44
Duplicate of #336 ?

**Comment by librafrog** [comment] 2021-03-04 09:46
> Duplicate of #336 ?

Yep 😄, you're right. So it seems we can either linked them or I close this one

**Closed** 2021-03-15 16:00 UTC
