### ISSUE TITLE
Balena Etcher Repository returns 403 Forbidden

### ISSUE THREAD

**Issue by Lamera** [balena-io/etcher#3246] opened 2020-07-16 16:22 UTC
- **Etcher version:** 1.5.100
- **Operating system and architecture:** Ubuntu 20.04

The Etcher repository is returning this error for a while.

`Ign:8 https://dl.bintray.com/etcher/debian stable InRelease`
`Fehl:12 https://dl.bintray.com/etcher/debian stable Release                                        
  403  Forbidden [IP: 3.120.60.234 443]`

**I tried the following:**

- Removed the application
- Removed the apt key
- Removed the source in /etc/apt/sources.d/
- Tried again to install with: [https://github.com/balena-io/etcher#debian-and-ubuntu-based-package-repository-gnulinux-x86x64](https://github.com/balena-io/etcher#debian-and-ubuntu-based-package-repository-gnulinux-x86x64)

**Comment by BiNh0X** [comment] 2020-07-16 20:40
Same problem in Linux Mint 19.3

**Comment by schmidtw** [comment] 2020-07-17 15:32
Same problem for Fedora 32.
All the files are forbidden here:
https://dl.bintray.com/etcher/redhat/

The directory structure appears & is navigable, but the content appears to have the wrong file permissions.

**Comment by Luki72** [comment] 2020-07-17 19:13
Same problem on Debian testing.
There appears to be a file permission error on the server.

**Comment by steelcowboy** [comment] 2020-07-18 23:18
@Lamera please close this issue, it is a duplicate of #3244

**Closed** 2020-07-19 09:00 UTC
