### ISSUE TITLE
Missing directory in /opt during install - solved by symlink.

### ISSUE THREAD

**Issue by dmcardlenl** [balena-io/etcher#3640] opened 2021-11-24 01:48 UTC
- **Etcher version:** 1.5.117
- **Operating system and architecture:** Fedora 34 x86_64 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?** 

Missing directory in /opt during install - solved by symlink.
/usr/bin/balena-etcher-electron points to /opt/balena-etcher-electron/balena-etcher-electron
in /opt ln -s ./balenaEtcher ./balena-etcher-electron needed - or similar - YMMV.

**Comment by lurch** [comment] 2021-11-24 02:13
See also #3486

**Comment by dmcardlenl** [comment] 2021-11-24 09:02
Yes, I didn't think I'd be the first to encounter this...I'll look later...

**Comment by Alex313031** [comment] 2021-12-09 03:22
@lurch @dmcardlenl Yup. chmod: cannot access '/opt/balena-etcher-electron/chrome-sandbox this has been an issue for as long as I have used etcher on linux. It will still run fine without making a symlink or copying /opt/balenaEtcher to /opt/balena-etcher-electron, but it is annoying nonetheless. It is probably an artifact from the days when the .debs were called and installed to "balena-etcher-electron". With how nitpicky (a good thing) balena is about fixing little things here and there in etcher, you would think they would have resolved this a long time ago.

**Comment by bedawi** [comment] 2022-01-16 18:40
I can confirm this error on Fedora 35 when version 1.7.3-1 is installed from RPM.

This link is broken: 
```/usr/bin/balena-etcher-electron -> /opt/balena-etcher-electron/balena-etcher-electron```

To fix the problem I run:
```bash
sudo rm /usr/bin/balena-etcher-electron
sudo ln -s /opt/balenaEtcher/balena-etcher-electron /usr/bin/balena-etcher-electron
```

**Comment by raniesantos** [comment] 2022-04-25 05:20
Also on Fedora 35, same issue. Thanks @bedawi for that quick fix.

**Comment by dfunckt** [comment] 2023-07-12 11:18
Dupe of #3486

**Closed by dfunckt** 2023-07-12 11:18 UTC
