### ISSUE TITLE
why only run as root on Linux

### ISSUE THREAD

**Issue by btwise** [balena-io/etcher#3181] opened 2020-05-28 11:51 UTC
Through continuous attempts, it can be built normally under Linux, and dep, RPM and appimage binaries are also automatically packaged, but it can only be run with root permissions, and the chrome-sandbox will not automatically set 4755 permissions, so the ordinary account cannot be run. What needs to be modified?

**Comment by lurch** [comment] 2020-05-28 22:34
Duplicate of #3129 ?

https://github.com/balena-io/etcher/issues/3119#issuecomment-622989049 might have a fix?

**Comment by btwise** [comment] 2020-05-28 22:59
If there is no solution, it should be solved from the project script, rather than the user constantly typing the command

**Comment by zvin** [comment] 2020-05-29 09:46
Etcher works fine as a regular user, it'll only elevate the writer process when needed.
What do you mean when you say "it can only be run with root permissions" ?

**Comment by btwise** [comment] 2020-05-29 10:12
> Etcher works fine as a regular user, it'll only elevate the writer process when needed.
> What do you mean when you say "it can only be run with root permissions" ?
I mean is: if the etcher does not work properly without sudo, it will tell you that the chrome-shadbox does not have 755 permissions, and if it runs sudo, it will work fine

**Comment by lurch** [comment] 2020-05-29 11:02
@zvin The other issues I linked to suggest this might only be an issue on Debian 10 ? :shrug:

**Comment by thundron** [comment] 2020-05-29 17:02
What distro of Linux are you trying to run Etcher on?
What version of Etcher?

**Closed** 2020-09-28 11:46 UTC

**Comment by cow-firmware** [comment] 2022-01-05 11:47
I was running this on centOS, only could get the balena etcher window to appear when running as root, content was empty.
