### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by certitudes** [balena-io/etcher#3090] opened 2020-02-29 16:50 UTC
I tried to update the application, but it says the public key is not available.

"Reading package lists... Done 
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://dl.google.com/linux/chrome/deb stable Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 78BD65473CB3BD13
E: The repository 'https://deb.etcher.io stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details."

**Comment by LaurentDumont** [comment] 2020-02-29 17:29
I think there are some issues with the repository itself.

![image](https://user-images.githubusercontent.com/8936473/75612176-230d9e00-5aef-11ea-8814-484c1c08a36c.png)

**Comment by hollec** [comment] 2020-02-29 18:48
Duplicate of #3078

**Comment by lurch** [comment] 2020-03-02 12:07
BTW it looks like your NO_PUBKEY error is actually in relation to the http://dl.google.com/linux/chrome/deb repo. :eyes:

**Comment by thundron** [comment] 2020-03-02 16:14
Please refer to https://github.com/balena-io/etcher/issues/3078

**Closed by thundron** 2020-03-02 16:14 UTC
