### ISSUE TITLE
[Problem] Etcher Debian Repository Packages Way Out Of Date 

### ISSUE THREAD

**Issue by zero77** [balena-io/etcher#2593] opened 2019-01-04 15:10 UTC
- **Etcher version:** 1.4.4
- **Operating system and architecture:** 18.04 
- **Image flashed:** n/a
- **Do you see any meaningful error information in the DevTools?** no

After following 

> echo "deb https://deb.etcher.io stable etcher" | sudo tee /etc/apt/sources.list.d/etcher.list
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61
sudo apt-get update
sudo apt-get install etcher-electron

I am only using v1.4.4, i have also tried and update and upgrade but this did not help.

**Comment by thundron** [comment] 2019-01-04 16:40
Duplicate of https://github.com/balena-io/etcher/issues/2540

**Closed by thundron** 2019-01-04 16:40 UTC
