### ISSUE TITLE
Please Add .7z file format suport!

### ISSUE THREAD

**Issue by toneywoo** [balena-io/etcher#3615] opened 2021-10-17 14:41 UTC
I compress a usb img file use .7z file format for backup,and save my diak space.
But I moust uncompress the .7z file to write it to usb drive.
please add .7z file format suport!!

- **Etcher version:1.5.115** 
- **Operating system and architecture:Windows 10 ** 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?**

**Comment by lurch** [comment] 2021-10-17 20:50
Duplicate of #711 ?

**Closed** 2021-10-17 21:01 UTC
