### ISSUE TITLE
403 on  https://dl.bintray.com/etcher/debian stable Release

### ISSUE THREAD

**Issue by deogracia** [balena-io/etcher#3252] opened 2020-07-20 07:21 UTC
- **Etcher version:** 1.4.4
- **Operating system and architecture:** debian 9 / amd64
- **Image flashed:**  N/A
- **Do you see any meaningful error information in the DevTools?** N/A

same error as in #3078

**Comment by thundron** [comment] 2020-07-20 10:57
Duplicate of https://github.com/balena-io/etcher/issues/3244, we'll update that once it's solved

**Closed by thundron** 2020-07-20 10:57 UTC
