### ISSUE TITLE
Hi when i am flashing the image in sd card its shows error " something went wrong" please help. I am using windows 10 (64). I am sharing screenshot as well.

### ISSUE THREAD

**Issue by abhibhatia98** [balena-io/etcher#2882] opened 2019-08-19 10:27 UTC
Etcher version: ---1.5.53
windows 10(64)
Image flashed:--Jatson nano 

Hi when i am flashing the image in sd card its shows error " something went wrong" please help. I am using windows 10 (64). I am sharing screenshot as well.
Error message showing is 
Mon Aug 19 2019 15:53:42 GMT+0530 (India Standard Time) Flash error ({"error":{"name":"Error","message":"Couldn't clean the drive, Command failed: diskpart s n (code 2147942405)","stack":"Error: Couldn't clean the drive, Command failed: diskpart s n (code 2147942405)\n    at Object.<anonymous> (C:\\Users\\abhishekbhatia\\AppData\\Local\\Programs\\balena-etcher\\resources\\app.asar\\node_modules\\etcher-sdk\\build\\diskpart.js:96:23)\n    at Generator.throw (<anonymous>)\n    at rejected (C:\\Users\\abhishekbhatia\\AppData\\Local\\Programs\\balena-etcher\\resources\\app.asar\\node_modules\\etcher-sdk\\build\\diskpart.js:20:65)"},"applicationSessionUuid":"8c2bfd1a-0065-4575-9273-551fdbd37203","flashingWorkflowUuid":"0c3e6cbf-b15e-4cdf-a8d7-31837cc34674","flashInstanceUuid":"b9c47553-f4c2-4e64-a02f-76d566241f6d","image":"C:\\Users\\abhishekbhatia\\Downloads\\jetson-nano-sd-r32.2-2019-07-16.zip","drives":[{"size":31914983424,"isVirtual":false,"enumerator":"PCISTOR","logicalBlockSize":512,"raw":"\\\\.\\PhysicalDrive1","error":null,"isReadOnly":false,"displayName":"E:\\","blockSize":512,"isSCSI":true,"isRemovable":true,"device":"\\\\.\\PhysicalDrive1","busVersion":"2.0","isSystem":false,"busType":"SCSI","isCard":false,"isUSB":false,"devicePath":null,"mountpoints":[{"path":"E:\\"}],"description":"SDHC Card","isUAS":false}],"driveCount":1,"uuid":"b9c47553-f4c2-4e64-a02f-76d566241f6d","unmountOnSuccess":true,"validateWriteOnSuccess":true,"trim":false,"sample":0.1})

<img width="902" alt="Capture" src="https://user-images.githubusercontent.com/54257727/63258558-e9cfb800-c299-11e9-81fc-0f0775f2cd13.PNG">

-

**Comment by lurch** [comment] 2020-03-25 10:59
Duplicate of #2812 ?

**Closed** 2023-07-12 09:11 UTC
