### ISSUE TITLE
Window stays white, cant use etcher

### ISSUE THREAD

**Issue by peterge1998** [balena-io/etcher#3548] opened 2021-07-05 10:17 UTC
- **Etcher version:** 
- Using latest balena-etcher-2:1.5.120-1 from AUR
- **Operating system and architecture:** 
- Arch
- **Image flashed:** 
- nothing
- **Do you see any meaningful error information in the DevTools?** 
- Cant open etcher

running  it manually gives this:
```
➜  ~ balena-etcher-electron 
ready-to-show: 560.042ms
```
![grafik](https://user-images.githubusercontent.com/47355238/124456401-ee68c100-dd8a-11eb-90ea-af42f433dd80.png)

**Comment by lurch** [comment] 2021-07-05 10:50
> Using latest balena-etcher-2:1.5.120-1 from AUR

Duplicate of #3536 ?

**Comment by peterge1998** [comment] 2021-07-05 10:58
> > Using latest balena-etcher-2:1.5.120-1 from AUR
> 
> Duplicate of #3536 ?

Yes, didnt see that issue. It doesnt show the error when i try running it, but i will close my issue.

**Closed** 2021-07-05 10:58 UTC
