### ISSUE TITLE
Error on the first try on macOS Big Sur

### ISSUE THREAD

**Issue by Cyberbeni** [balena-io/etcher#3368] opened 2020-11-27 16:16 UTC
- **Etcher version:** 1.5.111
- **Operating system and architecture:** macOS 11.0.1 x64
- **Image flashed:** https://github.com/hoobs-org/hoobs-build/releases/download/v3.2.10/HOOBS-3.2.10-ARM7.zip (unzipped after downloaded)
- **Do you see any meaningful error information in the DevTools?** 
Relevant parts of the log: [-1606493902657.log](https://github.com/balena-io/etcher/files/5608812/-1606493902657.log)

It asked for password then for write access for removable drive then I instantly got this error. After retrying, it worked fine.

**Comment by zvin** [comment] 2020-11-30 12:19
Thanks for reporting this @Cyberbeni 
Closing as I think it's a duplicate of #3366 
This should be fixed in 1.5.112 which should be released this week.

**Closed by zvin** 2020-11-30 12:19 UTC
