### ISSUE TITLE
error 403 while updateing on Linux Mint 19.3 (Ubuntu 18.04 based)

### ISSUE THREAD

**Issue by ToomaiO** [balena-io/etcher#3087] opened 2020-02-27 13:04 UTC
- **Etcher version:** 
- **Operating system and architecture:** 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?**

**Comment by lurch** [comment] 2020-02-27 13:30
Duplicate of #3078

**Comment by thundron** [comment] 2020-02-27 15:01
Please refer to the other issue. Closing

**Closed by thundron** 2020-02-27 15:01 UTC
