### ISSUE TITLE
There is only a disk selection, please make a partition selection.

### ISSUE THREAD

**Issue by HalfNathan120** [balena-io/etcher#3569] opened 2021-07-30 17:56 UTC
I have a USB that has multiple partitions, but it's only disk selection only other than partition selection. I didn't want to get rid of my backup drive, game files, home files, program files, and my virtual machines. All I want is to select an operating system setup partition.
![Etcher 7_30_2021 10_54_02 AM_LI](https://user-images.githubusercontent.com/85643430/127693095-f19e4535-5358-40df-81a9-e100910e0834.jpg)

**Comment by lurch** [comment] 2021-07-30 19:46
Duplicate of #3415

**Closed** 2021-08-20 05:30 UTC
