### ISSUE TITLE
"balenaEtcher" can't be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by kunau** [balena-io/etcher#2926] opened 2019-10-11 22:57 UTC
- **Etcher version:** == 1.5.58

![Screen Shot 2019-10-11 at 5 54 00 PM](https://user-images.githubusercontent.com/656846/66689423-5fc81e00-ec50-11e9-8921-d1409d7933f2.png)

![Screen Shot 2019-10-11 at 5 56 25 PM](https://user-images.githubusercontent.com/656846/66689441-75d5de80-ec50-11e9-8f66-efc6b328dae1.png)

- **Operating system and architecture:** 
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?**

**Comment by kunau** [comment] 2019-10-11 22:58
OS== OSX Catalina

The application will not start up, so there was no image about to be flashed.
DevTools not available because the application will not start.

**Comment by benhichak** [comment] 2019-10-12 00:43
Seeing the same issue. 

Etcher v1.5.58
MacOS v10.15 (Catalina)

**Comment by radeksalomon** [comment] 2019-10-12 12:44
This is not an issue. You can start the app by right clicking on the app and click Open. This will bypass the Apple's security check and app will start. It works with every app you need to start if it does not pass the security check. This procedure has to be done only during the first start of newly downloaded app.

**Comment by erikhermesman** [comment] 2019-10-12 21:27
On Catalina, I'm having to right click and open twice. The first time tells me it can't be opened, and the second time I do a right click - open, the dialogue box allows me to open the app.

**Comment by lurch** [comment] 2019-10-14 08:02
See also #2833

**Comment by thundron** [comment] 2019-10-19 10:42
Closing as duplicate of #2833 , we have a PR open that will solve issues with macOS Catalina

**Closed by thundron** 2019-10-19 10:42 UTC
