### ISSUE TITLE
Add Ability In-App Updates

### ISSUE THREAD

**Issue by TurannUl** [balena-io/etcher#3302] opened 2020-09-17 05:04 UTC
- **Etcher version:** 1.5.102
- **Operating system and architecture:** MacOS 11.0 x86_64
- **Image flashed:** yes
- **Do you see any meaningful error information in the DevTools?** there no error Just request I like your Project

**Comment by lurch** [comment] 2020-09-17 07:50
Duplicate of #336 ?

**Comment by TurannUl** [comment] 2020-09-17 19:53
Maybe I'dont readed #336, Only Askin

**Comment by thundron** [comment] 2020-10-13 17:57
Yep @lurch , closing

**Closed by thundron** 2020-10-13 17:57 UTC
