### ISSUE TITLE
Unexpected errors on MacOS 10.15.1

### ISSUE THREAD

**Issue by wpzhhhhh** [balena-io/etcher#2957] opened 2019-11-01 08:42 UTC
- **Etcher version:1.5.0** 
- **Operating system and architecture:MacOS 10.15.1** 
- **Image flashed: Raspbian Desktop** 
- **Do you see any meaningful error information in the DevTools?**
![截屏2019-11-0116 33 02](https://user-images.githubusercontent.com/44501215/68012538-4d785780-fcc5-11e9-9eb1-64c08c7ee8eb.png)

I've tried solution in #2954 and #2833, put iso file into balenaEtcher.app but an unexpected error shows.

**Comment by simonmeusel** [comment] 2019-11-01 21:23
`sudo /Applications/balenaEtcher.app/Contents/MacOS/balenaEtcher`

**Comment by lurch** [comment] 2019-11-02 14:07
I believe the Etcher developers are already working on fixes for macOS Catalina?
#2939 #2953

**Comment by flakerimi** [comment] 2019-11-05 11:58
This just happened to me.  

sudo /Applications/balenaEtcher.app/Contents/MacOS/balenaEtcher

Will ask you if you allow Catalina to access USB Drive. After clicking ok will continue.

Look for something like this:

![image](https://user-images.githubusercontent.com/871482/68206002-f37cd800-ffcb-11e9-8928-2dca25226e52.png)

**Comment by zvin** [comment] 2019-11-06 02:03
Duplicate of #2833

**Closed by zvin** 2019-11-06 02:03 UTC
