### ISSUE TITLE
Etcher not running

### ISSUE THREAD

**Issue by kovkus** [balena-io/etcher#3058] opened 2020-02-04 23:56 UTC
- **Etcher version:** 1.5.74
- **Operating system and architecture:** MacOS 10.14.6
- **Do you see any meaningful error information in the DevTools?** 
|  ___| |     | |
| |__ | |_ ___| |__   ___ _ __
|  __|| __/ __| '_ \ / _ \ '__|
| |___| || (__| | | |  __/ |
\____/ \__\___|_| |_|\___|_|

Version = 1.5.74, Type = dmg
/Applications/balenaEtcher.app/Contents/Resources/app/node_modules/raven-js/dist/raven.js:58 Wed Feb 05 2020 00:54:58 GMT+0100 (Central European Standard Time) Application start ({"packageType":"dmg","version":"1.5.74","applicationSessionUuid":"b03426ef-29a8-4641-b9b3-b787387bfca3","sample":0.1})
/Applications/balenaEtcher.app/Contents/Resources/app/node_modules/raven-js/dist/raven.js:58 {"stack":"TypeError: Cannot convert undefined or null to object\n    at Function.entries (<anonymous>)\n    at Object.init (file:///Applications/balenaEtcher.app/Contents/Resources/app/generated/gui.js:3951:49)\n    at main (file:///Applications/balenaEtcher.app/Contents/Resources/app/generated/gui.js:3633:12)","message":"Cannot convert undefined or null to object"}

**Comment by lurch** [comment] 2020-02-05 00:00
Probably a duplicate of #3057 ?

**Closed** 2020-02-05 12:35 UTC
