### ISSUE TITLE
E: The repository 'https://deb.etcher.io stable Release' is not signed.

### ISSUE THREAD

**Issue by swipswaps** [balena-io/etcher#3422] opened 2021-01-28 14:32 UTC
- **Etcher version:** 
- **Operating system and architecture:** 
MX Linux
Linux mx 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+mx17+1 (2019-11-17) x86_64 GNU/Linux
- **Image flashed:** 
- **Do you see any meaningful error information in the DevTools?**

**Comment by Tim-Hobbes** [comment] 2021-02-15 19:11
You probably forgot to trust Bintray.com's GPG key. This can be done by running this command: `sudo apt-key adv --keyserver hkps://keyserver.ubuntu.com:443 --recv-keys 379CE192D401AB61`

**Comment by thundron** [comment] 2021-02-16 09:10
correct, duplicate of https://github.com/balena-io/etcher/issues/2187, closing

**Closed by thundron** 2021-02-16 09:10 UTC

**Comment by Bkroland19** [comment] 2021-08-09 03:44
didnt get a solution

**Comment by lurch** [comment] 2021-08-10 08:40
@Bkroland19 AFAIK https://deb.etcher.io shouldn't be used any more. See #3501
