### ISSUE TITLE
Portable Version Doesn't Seem to be Portable

### ISSUE THREAD

**Issue by teamayu** [balena-io/etcher#3125] opened 2020-04-22 17:31 UTC
The portable version doesn't seem to be portable:
AppData/Roaming/balena-etcher/*

Loads of files/folders in the AppData folder. How do I make the portable version portable?

**Comment by lurch** [comment] 2020-04-23 10:23
Duplicate of #2871 ?

**Comment by thundron** [comment] 2020-04-24 09:25
Unfortunately, that's how the packager works for now, it just uses standard folders.
Please see the other issue for more infos, closing as duplicate

**Closed by thundron** 2020-04-24 09:25 UTC

**Comment by chocmake** [comment] 2023-02-26 09:58
> Duplicate of #2871 ?

That issue currently 404s. Found it also writes to the registry: `HKEY_CLASSES_ROOT\etcher` where it contains the path to the copy of the executable that is placed in the %temp% directory.

Perhaps could have a note/tooltip icon beside the portable download to clarify it's not portable in the typical Windows sense (ie: writing data only to the the same, user-configured directory that the executable is contained within, such as on a USB drive, and not elsewhere on the system).

**Comment by Mansarde** [comment] 2023-04-22 18:29
> Unfortunately, that's how the packager works for now, it just uses standard folders. Please see the other issue for more infos, closing as duplicate

Can you tell us the title of the issue? Because as @chocmake said, the link/issue is not available.
Thanks in advance!
