### ISSUE TITLE
Application not opening

### ISSUE THREAD

**Issue by MasterDiggi** [balena-io/etcher#3537] opened 2021-06-22 18:01 UTC
I installed Etcher normally, but when I try to execute it nothing happens even tho it's an active process

**Comment by diablos6p** [comment] 2021-07-04 10:27
can you post the terminal output of those two commands.
ls -l | grep balena
sudo ls -l /opt | grep balena
I had the same problem and it turned out that there was a problem with the shortcut link.

**Comment by lurch** [comment] 2021-07-04 10:34
@MasterDiggi What OS are you running on? What version of Etcher are you using?

**Comment by MasterDiggi** [comment] 2021-07-13 17:55
> can you post the terminal output of those two commands.
> ls -l | grep balena
> sudo ls -l /opt | grep balena
> I had the same problem and it turned out that there was a problem with the shortcut link.

I'm not using Linux, I'm using windows

**Comment by MasterDiggi** [comment] 2021-07-13 17:56
> @MasterDiggi What OS are you running on? What version of Etcher are you using?

I'm using Windows 10 Pro and I'm using the latest version of Etcher

**Comment by MasterDiggi** [comment] 2021-07-13 17:58
this is how the app stays - https://imgur.com/a/GuFCBvd

**Comment by lurch** [comment] 2021-07-13 20:21
Sounds very similar to #3088 ?

**Comment by diablos6p** [comment] 2021-07-18 09:44
did you try to use an older version of the app?
you can find them here: https://github.com/balena-io/etcher/releases

**Comment by MasterDiggi** [comment] 2021-07-27 02:36
> did you try to use an older version of the app?
> you can find them here: https://github.com/balena-io/etcher/releases

ok yes I've tried using old versions and the only place I could use it was on my Linux laptop and when I restart my pc trying to open the app as fast as possible

**Comment by thundron** [comment] 2021-08-20 05:33
sounds like a duplicate of #3088 as mentioned, closing this one

**Closed by thundron** 2021-08-20 05:33 UTC
