### ISSUE TITLE
Blank screen with "noexec" /tmp [failed to map segment from shared object]

### ISSUE THREAD

**Issue by szotsaki** [balena-io/etcher#2569] opened 2018-11-29 06:24 UTC
- **Etcher version:** Version = 1.4.8, Type = rpm
- **Operating system and architecture:** openSUSE Tumbleweed, x64
- **Image flashed:**  --
- **Do you see any meaningful error information in the DevTools?** 

When I start Etcher.io with `noexec` /tmp directory, the following appears in console log and the main screen remains gray:

```
Uncaught Error: /tmp/.org.chromium.Chromium.3sv1Wp: failed to map segment from shared object
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:187:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /opt/balenaEtcher/resources/app.asar/node_modules/lzma-native/index.js:11:14
    at Object.<anonymous> (/opt/balenaEtcher/resources/app.asar/node_modules/lzma-native/index.js:623:3)
    at Object.<anonymous> (/opt/balenaEtcher/resources/app.asar/node_modules/lzma-native/index.js:625:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by lurch** [comment] 2018-11-30 09:10
Duplicate of #1699 ?

**Closed** 2023-07-12 09:13 UTC
