### ISSUE TITLE
Setup script won't run on Devuan Linux

### ISSUE THREAD

**Issue by phaoost** [balena-io/etcher#3776] opened 2022-06-17 14:29 UTC
```
~$ curl -1sLf 'https://dl.cloudsmith.io/public/balena/etcher/setup.deb.sh' |distro=devuan  version=4  codename=chimaera  arch=x86_64 sudo -E bash
Executing the  setup script for the 'balena/etcher' repository ...

   OK: Checking for required executable 'curl' ...
   OK: Checking for required executable 'apt-get' ...
   OK: Checking for apt dependency 'apt-transport-https' ...
   OK: Checking for apt dependency 'ca-certificates' ...
   OK: Checking for apt dependency 'gnupg' ...
  RUN: Importing 'balena/etcher' repository GPG key ...gpg: WARNING: unsafe ownership on homedir '/home/user/.gnupg'
   OK: Checking for apt signed-by key support ...
   OK: Importing 'balena/etcher' repository GPG key ...
 NOPE: Checking if upstream install config is OK ...
 ^^^^: ... Failed to fetch configuration for your OS distribution release/version.
 >>>>:
 >>>>: It looks like we don't currently support your distribution release and
 >>>>: version. This is something that we can fix by adding it to our list of
 >>>>: supported versions (see contact us below), or you can manually override
 >>>>: the values below to an equivalent distribution that we do support:
 >>>>:
 >>>>: ... distro=devuan  version=4  codename=chimaera  arch=x86_64  
 >>>>:
 >>>>: You can force this script to use a particular value by specifying distro,
 >>>>: version, or codename via environment variable. E.g., to specify a distro
 >>>>: such as Ubuntu/Xenial (16.04), use the following:
 >>>>:
 >>>>:   <curl command> | distro=ubuntu version=16.04 codename=xenial sudo -E bash
 >>>>:
 !!!!: Oh no, your setup failed! :-( ... But we might be able to help. :-)
 !!!!: 
 !!!!: You can contact balena for further assistance.
 !!!!: 
 !!!!: URL: https://github.com/balena-io/etcher
 !!!!: 
 !!!!: Last 20 log lines from .csm_setup_wgmVX6P2P (might not be errors, nor even relevant):
 !!!!:
 !!!!: > ii  gnupg                                         2.2.35-2
 !!!!: > all          GNU privacy guard - a free PGP replacement
 !!!!: > ii  gnupg-l10n                                    2.2.35-2
 !!!!: > all          GNU privacy guard - localization files
 !!!!: > ii  gnupg-utils                                   2.2.35-2
 !!!!: > amd64        GNU privacy guard - utility programs
```

**Comment by mcraa** [comment] 2022-06-17 15:10
duplicate of #3663 and many similar

read the [install instructions](https://cloudsmith.io/~balena/repos/etcher/setup/#formats-rpm) and your error message
```
 >>>>: It looks like we don't currently support your distribution release and
 >>>>: version. This is something that we can fix by adding it to our list of
 >>>>: supported versions (see contact us below), or you can manually override
 >>>>: the values below to an equivalent distribution that we do support:
 >>>>:
 >>>>: ... distro=devuan  version=4  codename=chimaera  arch=x86_64  
 >>>>:
 >>>>: You can force this script to use a particular value by specifying distro,
 >>>>: version, or codename via environment variable. E.g., to specify a distro
 >>>>: such as Ubuntu/Xenial (16.04), use the following:
 >>>>:
 >>>>:   <curl command> | distro=ubuntu version=16.04 codename=xenial sudo -E bash
```

> If you need to force a specific distribution, release/version, or even architecture, you can also do that (e.g. if your system is compatible but not identical):
```
curl -1sLf \
  'https://dl.cloudsmith.io/public/balena/etcher/setup.rpm.sh' \
  | sudo -E distro=some-distro codename=some-codename arch=some-arch bash
```
find out what devuan is based on and replace `some-distro` with that name (hint: `debian`)

**Closed by mcraa** 2022-06-17 15:10 UTC
